import { createContext } from "react";

export type Idioma = "en" | "pt";

export type IdiomaContextType = {
  idioma: Idioma;
  alternarIdioma: () => void;
  traduzir: (chave: ChaveTexto) => string;
};

export const textosEn = {
  projects: "Projects",
  about: "About me",
  contact: "Contact",
  tools: "Tools",
  resume: "Resume",
  curriculum: "CV",
  bin: "Bin",
  empty: "Empty",
  start: "Start",
  startMenu: "Start menu",
  switchLanguage: "Mudar para português",
  aboutFile: "ABOUT ME.TXT",
  greeting: "Hi! I’m Victor...",
  job: "Software Engineering Student",
  focus: "Focus",
  focusValue: "Full-stack development",
  availability: "Open to new opportunities",
  softwareDeveloper: "Software Developer",
  bioOne: "build web applications and back-end systems,",
  bioTwo: "work with databases and embedded systems, and",
  bioThree: "enjoy turning ideas into real projects.",
  name: "Name",
  role: "Role",
  resumeFile: "RESUME.TXT",
  resumeTitle: "Software Engineering Student / Web Developer",
  location: "Curitiba, Brazil",
  degree: "Software Engineering",
  education: "Education",
  currentStack: "Current stack",
  workExperience: "Work Experience",
  inProgress: "2025 - In progress",
  none: "None",
  languages: "Languages",
  frameworks: "Frameworks",
  repository: "Repository",
  demo: "Demo",
  email: "Email",
  phone: "Phone",
  sendEmail: "Send email",
  sendMessage: "Send message",
  minimize: "Minimize",
  maximize: "Maximize",
  restore: "Restore",
  close: "Close",
  open: "Open",
  downloadResume: "Download CV",
  fileComingSoon: "The PDF will be available soon.",
} as const;

export type ChaveTexto = keyof typeof textosEn;

export const textosPt: Record<ChaveTexto, string> = {
  projects: "Projetos",
  about: "Sobre mim",
  contact: "Contato",
  tools: "Tecnologias",
  resume: "Currículo",
  curriculum: "Currículo",
  bin: "Lixeira",
  empty: "Vazia",
  start: "Iniciar",
  startMenu: "Menu Iniciar",
  switchLanguage: "Switch to English",
  aboutFile: "SOBRE MIM.TXT",
  greeting: "Olá! Eu sou o Victor...",
  job: "Estudante de Engenharia de Software",
  focus: "Foco",
  focusValue: "Desenvolvimento full-stack",
  availability: "Aberto a novas oportunidades",
  softwareDeveloper: "Desenvolvedor de Software",
  bioOne: "desenvolvo aplicações web e sistemas back-end,",
  bioTwo: "trabalho com bancos de dados e sistemas embarcados e",
  bioThree: "gosto de transformar ideias em projetos reais.",
  name: "Nome",
  role: "Função",
  resumeFile: "CURRICULO.TXT",
  resumeTitle: "Estudante de Engenharia de Software / Desenvolvedor Web",
  location: "Curitiba, Brasil",
  degree: "Engenharia de Software",
  education: "Formação",
  currentStack: "Stack atual",
  workExperience: "Experiência profissional",
  inProgress: "2025 - Em andamento",
  none: "Nenhuma",
  languages: "Linguagens",
  frameworks: "Frameworks",
  repository: "Repositório",
  demo: "Demonstração",
  email: "E-mail",
  phone: "Telefone",
  sendEmail: "Enviar e-mail",
  sendMessage: "Enviar mensagem",
  minimize: "Minimizar",
  maximize: "Maximizar",
  restore: "Restaurar",
  close: "Fechar",
  open: "Abrir",
  downloadResume: "Baixar currículo",
  fileComingSoon: "O PDF estará disponível em breve.",
};

export const IdiomaContext = createContext<IdiomaContextType | null>(null);
